name: Build, Test, and Deploy

on:
  pull_request:
  workflow_dispatch: # Add this to allow manual or external triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

        # Install Git LFS (in case it's not already installed)
      - name: Install Git LFS
        run: |
          git lfs install
          git lfs pull  # Fetch the LFS files if not already fetched

      - name: Set Node Version
        uses: actions/setup-node@v4
        with:
          node-version: lts/iron

      - name: Install
        run: npm ci

      - name: Build
        run: |
          npm run build --if-present
        env:
          CI: true

      - name: E2E Prepare
        run: |
          npm run e2e:prepare --if-present
        env:
          CI: true

      - name: E2E
        run: |
          npm run vrt --if-present
        env:
          CI: true
